### ISSUE TITLE
Attachments in the wrong category

### ISSUE THREAD

**Issue by cekdat1** [Hood26/TheGambler#1]
Might just be a minor change, but all the attachments are in the wrong category, is this able to be fixed?
Its really a pain in the butt if you are using a mod such as : https://hub.sp-tarkov.com/files/file/2122-inventory-organizing-features-3-9-0/#overview

![Screenshot 2024-09-18 120210](https://github.com/user-attachments/assets/a6dfd0e1-695b-40fc-97ce-57f6da1a8499)

**Comment by Hood26** [comment]
This has already been fixed and would have been included in the next update 0.3.0, but since many have pointed out this problem I'll re-upload the 0.2.5 files which will include this fix. You'll just have to re download the 0.2.5 version
